### YamlMime:FAQ
metadata:
  title: Forum aux questions sur le déploiement centralisé
  f1.keywords:
  - NOCSH
  ms.author: kwekua
  author: kwekua
  manager: scotv
  audience: Admin
  ms.topic: faq
  ms.service: o365-administration
  ms.localizationpriority: medium
  ms.collection:
  - M365-subscription-management
  - Adm_O365
  - Adm_NonTOC
  - Adm_TOC
  ms.custom: AdminSurgePortfolio
  search.appverid:
  - BCS160
  - MET150
  - MOE150
  description: Passez en revue les réponses aux questions fréquentes sur le déploiement centralisé à partir du Centre d'administration Microsoft 365.
  ms.openlocfilehash: 6aaaf75003e3d376e7b92b68ea006f75dcdffd3a
  ms.sourcegitcommit: 13a1199fbfeb329da77ce87b2781d5cc77e4a201
  ms.translationtype: MT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 07/27/2022
  ms.locfileid: "67037476"
title: Forum aux questions sur le déploiement centralisé
summary: Le déploiement centralisé est le moyen recommandé pour un administrateur Office 365 de déployer des compléments Office (Word, Excel, PowerPoint et Outlook) sur des utilisateurs et des groupes au sein d’une organisation, à condition que l’organisation réponde à toutes les exigences d’utilisation du déploiement centralisé, comme décrit dans cet article.
sections:
- name: Ignoré
  questions:
  - question: >
      Comment faire savoir si mon organisation est configurée pour le déploiement centralisé ?
    answer: "Le déploiement centralisé des compléments nécessite que les utilisateurs utilisent Applications Microsoft 365 pour les grandes entreprises (et qu’ils soient connectés à Office à l’aide de leurs informations d’identification de connexion d’organisation) et disposent de boîtes aux lettres Exchange Online. Votre annuaire d’abonnement doit être dans Azure Active Directory ou fédéré vers ce dernier. \n \nLe déploiement centralisé est uniquement pris en charge pour les boîtes aux lettres en ligne. Il ne prend pas en charge le déploiement sur des boîtes aux lettres Exchange locales.\n\nVous pouvez utiliser le [vérificateur de compatibilité de déploiement centralisé](centralized-deployment-of-add-ins.md#centralized-deployment-compatibility-checker) pour déterminer si votre abonnement est éligible. \n  \n"
  - question: >
      Comment cibler les affectations d’utilisateurs de complément avec le déploiement centralisé ?
    answer: "Le déploiement centralisé prend en charge les affectations à des utilisateurs individuels, à des groupes et à tous les membres du locataire. Le déploiement centralisé peut être utilisé pour les utilisateurs de groupes de niveau supérieur ou sans groupes parents, mais pas pour les utilisateurs des groupes imbriqués ou des groupes qui ont des groupes parents. Le déploiement centralisé fait également partie de la plupart des groupes Azure Active Directory, notamment les groupes Office 365, les listes de distribution, les groupes dynamiques et les groupes de sécurité. \n\nIl est préférable d’utiliser des affectations de groupes plutôt que des affectations d’utilisateurs individuelles pour faciliter la gestion.\n \nPour plus d’informations, consultez [Attributions d’utilisateurs et de groupes](./centralized-deployment-of-add-ins.md?view=o365-worldwide#user-and-group-assignments).\n \n"
  - question: >
      Combien de temps faut-il pour que les compléments s’affichent pour tous les utilisateurs ?
    answer: >
      L’affichage d’un nouveau déploiement de complément peut prendre jusqu’à 24 heures pour tous les utilisateurs. Jusqu’à 72 heures peuvent être nécessaires pour que les mises à jour des compléments, les modifications apportées à l’activation ou à la désactivation, ou les suppressions de compléments soient reflétées pour les utilisateurs.
  - question: >
      En tant qu’administrateur, comment gérer l’accès utilisateur aux compléments pour mon organisation ?
    answer: >
      Pour faciliter le déploiement des compléments pour les utilisateurs, les groupes ou l’ensemble de votre organisation, nous recommandons aux administrateurs d’utiliser le déploiement centralisé.


      Pour plus d’informations sur la gestion de l’accès utilisateur, consultez :
       - [Empêcher les téléchargements de compléments en désactivant l’Office Store sur tous les clients (à l’exception d’Outlook)](./manage-addins-in-the-admin-center.md#prevent-add-in-downloads-by-turning-off-the-office-store-across-all-clients-except-outlook)
       - [Désignation des administrateurs et utilisateurs qui peuvent installer et gérer des compléments pour Outlook](/Exchange/specify-who-can-install-and-manage-add-ins-2013-help)
  - question: "Le déploiement centralisé donnera-t-il aux administrateurs la possibilité de choisir la méthode de déploiement pour les compléments Outlook ? \n"
    answer: "Oui. Le déploiement centralisé offre aux administrateurs la possibilité de choisir l’une des deux méthodes de déploiement pour les compléments Outlook pendant le déploiement du complément :\n         \n**Disponible** Les utilisateurs peuvent installer le complément dans Outlook en choisissant **Accueil > Obtenir d’autres compléments > Administration gérés**.\n \n**Optionnel** Le complément est déployé automatiquement sur les utilisateurs affectés, mais ils peuvent choisir de le supprimer.\n    \n"
  - question: "Les administrateurs peuvent-ils mettre à jour les compléments métier ? \n"
    answer: "Oui. Les administrateurs peuvent charger un nouveau fichier manifeste pour prendre en charge les modifications de métadonnées pour les compléments métier déployés par l’administrateur. Le complément est mis à jour lors du prochain démarrage des applications Office. L'application web peut changer à tout moment.\n \nPour plus d’informations, consultez le [complément métier](./manage-addins-in-the-admin-center.md).  \n"
  - question: "Les administrateurs peuvent-ils désactiver les compléments ? \n"
    answer: >
      Oui. Les administrateurs peuvent activer ou désactiver les compléments qu’ils déploient pour tous les utilisateurs à partir du Centre d’administration Microsoft.


      Pour plus d’informations, consultez [États du complément](./manage-addins-in-the-admin-center.md#add-in-states).
  - question: >
      Les administrateurs peuvent-ils supprimer ou supprimer des compléments ?
    answer: "Oui. Les administrateurs peuvent supprimer des compléments qu’ils ont déployés pour tous les utilisateurs à partir du Centre d’administration Microsoft.\n\nPour plus d’informations, consultez [Supprimer un complément](./manage-addins-in-the-admin-center.md#delete-an-add-in). \n  \n"
  - question: "Les administrateurs peuvent-ils déployer des compléments payants à partir de l’Office Store à l’aide d’un déploiement centralisé ? \n"
    answer: "Non. Vous ne pouvez pas déployer de compléments payants à partir de l’Office Store à l’aide du déploiement centralisé pour l’instant. \n \nNous vous suggérons de contacter le développeur isv pour que le complément payant demande un fichier manifeste ou une URL. L’administrateur client peut ensuite déployer le complément en tant que complément métier à l’aide du déploiement centralisé.\n   \n"
  - question: "Quel rôle d’administrateur dois-je gérer les compléments pour mon organisation ? \n"
    answer: "La Administration globale est le rôle recommandé avec un accès complet au cycle de vie de gestion des compléments. Si vous êtes la personne qui a acheté votre abonnement Microsoft 365 Business, vous êtes l’administrateur général.\n\nVotre abonnement est fourni avec un ensemble de rôles d’administrateur que vous pouvez attribuer à d’autres utilisateurs de votre organisation. Chaque rôle d’administrateur est mappé à des fonctions métier courantes et donne aux membres de votre organisation les autorisations nécessaires pour effectuer des tâches spécifiques dans le Centre d'administration Microsoft 365.  \n \nPour plus d’informations, consultez [Attribuer des rôles d’administrateur](../add-users/assign-admin-roles.md?view=o365-worldwide).\n   \n"
  - question: >
      Combien de compléments puis-je déployer ?
    answer: Au total, 200 compléments Excel, Outlook, PowerPoint et Word peuvent être déployés par des administrateurs au sein de leur locataire.
